A = int(imput("Choose a number"))
B = int(imput("Choose another number"))
C = int(imput("Choose and another number"))
print("The number A is " + str(A) + ". The number B is " + str(B) + ". The number C is " + str(C))
high = max(A,B,C)
print("The largest number is " + str(high))
